In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('Mail Data.csv')

In [2]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
# importing all dependencies

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer # to convert the data into numbers
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
# replace the null values with a null string
mail_data = df.where((pd.notnull(df)),'')
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
# label spam mail as 0 , ham mail as 1
mail_data['Category']=mail_data['Category'].astype(int)

mail_data.loc[mail_data['Category'] == 'spam', 'Category'] = 0
mail_data.loc[mail_data['Category'] == 'ham' , 'Category'] = 1

In [10]:
x=mail_data['Message']
y=mail_data['Category']

In [11]:
# split data into training and testing data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [19]:
# transform the text data to feature vectors that can be used as input to logistic regression
feature_extraction = TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)
x_train_features=feature_extraction.fit_transform(x_train)
x_test_features=feature_extraction.transform(x_test)

In [24]:
model=LogisticRegression()
model.fit(x_train_features,y_train)
print(x_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34775 stored elements and shape (4457, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347
  (1, 3811)	0.17419952275504036
  (1, 3046)	0.25037127926135183
  (1, 1991)	0.3303699595553703
  (1, 2956)	0.3303699595553703
  (1, 2758)	0.32264078859437995
  (1, 1839)	0.27849035905614555
  (1, 918)	0.22871581159877652
  (1, 2746)	0.33982970028640835
  (1, 2957)	0.33982970028640835
  (1, 3325)	0.3161058676607887
  (1, 3185)	0.2969448295769459
  (1, 4080)	0.18880584110891166
  (2, 6601)	0.6056811524587518
  (2, 2404)	0.45287711070606745
  (2, 3156)	0.4107239318312698
  (2, 407)	0.509272536051008
  (3, 7414)	0.8100020912469564
  (3, 2870)	0.5864269879324768
  (4, 2870)	0.4187214730932375
  (4, 487)	0.28991184217461985
  :	:
  (4454, 2855)	0.47210665083641806
  (4454, 2246)	0.47210665083641806
  (4455, 4456)	0.24920025316220423
  (4455, 3922)	0.31287563163368587
  (4455, 6916)	0.19636985317119715
  (4455, 4715)	0.30714144758811196
  (4455, 3872)	0.3108911491788658
  (4455, 7113)	0.30536590342067704
  (4455, 6091)	0.23103841516927642
  (4455, 6810)	0.29731757715898277
  (4455, 5646)	0.33545678464631296
  (4455, 2469)	0.35441545511837946
  (4455, 2247)	0.37052851863170466
  (4456, 2870)	0.31523196273113385
  (4456, 5778)	0.16243064490100795
  (4456, 334)	0.2220077711654938
  (4456, 6307)	0.2752760476857975
  (4456, 6249)	0.17573831794959716
  (4456, 7150)	0.3677554681447669
  (4456, 7154)	0.24083218452280053
  (4456, 6028)	0.21034888000987115
  (4456, 5569)	0.4619395404299172
  (4456, 6311)	0.30133182431707617
  (4456, 647)	0.30133182431707617
  (4456, 141)	0.292943737785358

In [25]:
y_train_pred=model.predict(x_train_features)
y_test_pred=model.predict(x_test_features)

In [26]:
accuracy_train=accuracy_score(y_train,y_train_pred)
accuracy_test=accuracy_score(y_test,y_test_pred)
print(accuracy_train,accuracy_test)

0.9676912721561588 0.9668161434977578

In [27]:
# predicting using our own input
input_mail=["7 Days Only!Extra Savings For Your Mid-Year Break!Hi jiya bansal,The mid-year break is almost here. It's now time to plan your Singapore city escape.For one week only, enjoy an additional 5% OFF our Advance Purchase rates and unlock even greater value for your upcoming urban holiday getaway."]


input_data_features = feature_extraction.transform(input_mail)
prediction=model.predict(input_data_features)
if (prediction==1):
    print("ham")
else:
    print("spam")

spam